spring:
  application:
    name: gateway-zuul
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 上线之后需要使用以下配置
      # defaultZone: http://eureka-server:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    order-service:
      path: /order-service/**
      serviceId: order-service