spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lcoalhost:3306/microservice_mallmanagement
    # 与docker整合需要以下配置（也可以使用具体的端口号）
    # url: jdbc:mysql://mysql:3306/microservice_mallmanagement
    username: root
    password: 123456
  application:
    name: order-service
server:
  port: 7900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 上线测试用以下配置
      # defaultZone: http://eureka-server:8761/eureka/
mybatis:
  type-aliases-package: com.demo.order.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    cache-enabled: true
    call-setters-on-nulls: true
    default-executor-type: simple
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true